config/routes.rb
Rails.application.routes.draw do
  root to: 'restaurants#home'

  get 'home', to:'restaurants#home', as: :home
  resources :restaurants, only: [:index] do
    put 'kitchen', to: 'restaurants#kitchen', as: :kitchen
    get 'dashboard', to:'restaurants#dashboard', as: :dashboard
    get 'statistics/turnover', to:'restaurants#turnover', as: :turnover
    get 'statistics/metrics', to:'restaurants#metrics', as: :metrics
    resources :tables, only: [:index, :show] do

      resources :items, only: [:index]
      get 'items/basket', to:'items#basket_summary', as: :basket_summary
      get 'items/confirmation/orders/:id', to:'items#confirmation_summary', as: :confirmation_summary

      resources :orders, only: [:index, :update, :destroy] do
        resources :payments, only: [:new, :create]
      end
      delete 'orders', to:'orders#clear_table', as: :clear
      get 'orders/:id/delivered', to:'orders#delivered', as: :order_delivered
      get 'orders/:id/paid', to:'orders#paid', as: :order_paid
      get 'orders/:id/ticket', to: 'orders#ticket', as: :order_ticket

      resources :orderlines, only: [:create, :destroy]
      put 'orderlines/:id/increase', to:'orderlines#increase_item', as: :increase_item
      put 'orderlines/:id/decrease', to:'orderlines#decrease_item', as: :decrease_item
      delete 'orderlines/:id/cancel', to:'orderlines#cancel_item', as: :cancel_item

    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(255, 240, 0, 0.2) 0%, rgba(62, 54, 0, 0.3) 30%), url(<%= image_path "#{@restaurant.id}.jpg"%>); background-position: center;">
  <div class="banner-content">
    <% if @restaurant.kitchen %>
    <h1><%= @restaurant.name %> </h1>
    <% else %>
    <h1>Sorry the kitchen is closed</h1>
    <h4> We are open every day between 6pm and 10pm</h4>
    <% end %>
  </div>
</div>

<% if @restaurant.kitchen %>
<a href="#" class="scroll-down" address="true"></a>
<section class="ok">
<% end %>

app/views/shared/_bin.html.erb
<!-- <div id="linetop" class="box"><h3>Restaurant Dashboard</h3></div> -->

    <!-- <div class="orderstat box">
      <div>
        <h5>Orders Pending</h5>
      </div>
      <% @orders_pending.each do |order| %>
      <div>
        <div class="panel-group">
          <div class="panel panel-default">
            <div class="panel-heading">
              <div class="dashboard-order">
                <a class="dash" data-toggle="collapse" href="#collapse-<%=  order.id %>">
                  <span class="words-dashboard">
                  </span>
                  <span class="words-dashboard">
                    Table <%= order.table.table_number %>
                  </span>
                  <span class="words-dashboard">
                    <%= (order.created_at + 60.minutes ).strftime("%H:%M") %>
                  </span>
                  <%= humanized_money_with_symbol(order.price_per_order) %>
                </a>
              </div>
            </div>
            <div id="collapse-<%=  order.id %>" class="panel-collapse collapse">
              <ul class="list-group">
                <% order.orderlines.each do |orderline| %>
                <li class="list-group-item"><%= orderline.quantity %> x <%= orderline.item.name %> - <%= humanized_money_with_symbol(orderline.quantity * orderline.item.price) %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div> -->

    <!-- <div id="linebtm" class="box">
      <% @tables.each do |table| %>
      <%= link_to "Table #{table.table_number}", restaurant_table_orders_path(@restaurant, table) , class: 'btn btn-dashboard' %>
      <% end %>
    </div> -->


<!-- <script> setTimeout(location.reload.bind(location), 30000); </script> -->

app/views/shared/_browser-tab-title.html.erb
<% content_for(:title_tag) do %>
   ChronosApp | <%= @restaurant.name %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <%= link_to "#{root_path}", class: "navbar-wagon-brand" do %>
    <%= image_tag "chronos.png" %>
  <% end %>
  <h2>Chronos</h2>
</div>

app/views/shared/_sidebar-left.html.erb
<style>
  .cutlery-icon::before {
    margin-left: 12px;
    margin-right: 10px;
  }

  .stats-icon::before {
    margin-left: 8px;
    margin-right: 3px;
  }

  .dash-icon::before {
   margin-right: 5px;
  }

</style>

<div class="nav-side-menu">

    <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>
    <div class="menu-list">
        <ul id="menu-content" class="menu-content collapse out">
            <li>
                <a href="#">
                    <i class="fa fa-dashboard fa-lg dash-icon"></i> Dashboard
                </a>
            </li>
            <li data-toggle="collapse" data-target="#products" class="collapsed active">
                <i class="fa fa-cutlery fa-lg cutlery-icon"></i>All Tables <span class="arrow"></span>
            </li>
            <ul class="sub-menu collapse" id="products">
                <li class="hidden"><a href="#">Tables</a></li>
                <% @tables.each do |table| %>
                  <li>
                   <%= link_to restaurant_table_orders_path(@restaurant, table) do %>
                    Table <%= table.table_number %>
                    <% end %>
                  </li>
                <% end %>
            </ul>



            <li data-toggle="collapse" data-target="#new" class="collapsed">
                <i class="fa fa-bar-chart fa-lg stats-icon"></i> Statistics <span class="arrow"></span>
            </li>
            <ul class="sub-menu collapse" id="new">
                <li><%= link_to "Turnover", restaurant_turnover_path(@restaurant) %></li>
                <li><%= link_to "Daily metrics", restaurant_metrics_path(@restaurant) %></li>
            </ul>

            <li>
                <% if @restaurant.kitchen == false  %>
              <%= link_to restaurant_kitchen_path(@restaurant), method: :put do %>
                <i class="fa fa-unlock fa-lg"></i> Open Kitchen
                <% end %>
              <% else %>
              <%= link_to restaurant_kitchen_path(@restaurant), method: :put do %>
                <i class="fa fa-lock fa-lg"></i> Close Kitchen
                <% end %>
              <% end %>
            </li>



            <li>
                <a href="#">
                    <i class="fa fa-user fa-lg"></i> Profile
                </a>
            </li>

        </ul>
    </div>
</div>
<!-- <div class="container" id="main">
    <div class="row">
        <div class="col-md-12">
            <h4>This is suppose to be in the main content</h4>
        </div>
    </div>
</div> -->

app/views/shared/_sidebar-right.html.erb
<div class="nav-side-right-menu">
  <div class="brand"> Key Metrics </div>

  <h4 style="text-align: center; margin-top: 50px;">Active Tables</h4>

  <div class="label label-default green-sideb"><%= @occupied_tables.to_i %>%</div>



  <h4 style="text-align: center; margin-top: 50px;">Active Orders</h4>


  <div class="label label-default orange-sideb"><%= @active_orders.count %></div>


  <h4 style="text-align: center; margin-top: 50px;">Unpaid Orders</h4>



  <div class="label label-default red-sideb"><%= @orders_not_yet_paid.count %></div>


</div>

<script>
$(function () {
  $('[data-toggle="popover"]').popover()
})
</script>

app/views/shared/_sidebar.html.erb
<style>
  .cutlery-icon::before {
    margin-left: 12px;
    margin-right: 10px;
  }

  .stats-icon::before {
    margin-left: 8px;
    margin-right: 3px;
  }

  .dash-icon::before {
   margin-right: 5px;
  }

</style>

<div class="nav-side-menu">
    <div class="brand"><%= image_tag 'chronos.png', :style => "width: 10%" %> Chronos </div>
    <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>
    <div class="menu-list">
        <ul id="menu-content" class="menu-content collapse out">
            <li>
                <a href="#">
                    <i class="fa fa-dashboard fa-lg dash-icon"></i> Dashboard
                </a>
            </li>
            <li data-toggle="collapse" data-target="#products" class="collapsed active">
                <i class="fa fa-cutlery fa-lg cutlery-icon"></i>All Tables <span class="arrow"></span>
            </li>
            <ul class="sub-menu collapse" id="products">
                <li class="hidden"><a href="#">Tables</a></li>
                <% @tables.each do |table| %>
                  <li>
                   <%= link_to restaurant_table_orders_path(@restaurant, table) do %>
                    Table <%= table.table_number %>
                    <% end %>
                  </li>
                <% end %>
            </ul>



            <li data-toggle="collapse" data-target="#new" class="collapsed">
                <i class="fa fa-bar-chart fa-lg stats-icon"></i> Statistics <span class="arrow"></span>
            </li>
            <ul class="sub-menu collapse" id="new">
                <li>Metric 1</li>
                <li>Metric 2</li>
                <li>Metric 3</li>
            </ul>

            <li>
                <% if @restaurant.kitchen == false  %>
              <%= link_to restaurant_kitchen_path(@restaurant), method: :put do %>
                <i class="fa fa-unlock fa-lg"></i> Open Kitchen
                <% end %>
              <% else %>
              <%= link_to restaurant_kitchen_path(@restaurant), method: :put do %>
                <i class="fa fa-lock fa-lg"></i> Close Kitchen
                <% end %>
              <% end %>
            </li>



            <li>
                <a href="#">
                    <i class="fa fa-user fa-lg"></i> Profile
                </a>
            </li>

        </ul>
    </div>
</div>
<!-- <div class="container" id="main">
    <div class="row">
        <div class="col-md-12">
            <h4>This is suppose to be in the main content</h4>
        </div>
    </div>
</div> -->