config/routes.rb
Rails.application.routes.draw do
  root to: 'restaurants#home'

  get 'home', to:'restaurants#home', as: :home
  resources :restaurants, only: [:index] do
    put 'kitchen', to: 'restaurants#kitchen', as: :kitchen
    get 'dashboard', to:'restaurants#dashboard', as: :dashboard
    get 'statistics/turnover', to:'restaurants#turnover', as: :turnover
    get 'statistics/metrics', to:'restaurants#metrics', as: :metrics
    resources :tables, only: [:index, :show] do

      resources :items, only: [:index]
      get 'items/basket', to:'items#basket_summary', as: :basket_summary
      get 'items/confirmation/orders/:id', to:'items#confirmation_summary', as: :confirmation_summary

      resources :orders, only: [:index, :update, :destroy] do
        resources :payments, only: [:new, :create]
      end
      delete 'orders', to:'orders#clear_table', as: :clear
      get 'orders/:id/delivered', to:'orders#delivered', as: :order_delivered
      get 'orders/:id/paid', to:'orders#paid', as: :order_paid
      get 'orders/:id/ticket', to: 'orders#ticket', as: :order_ticket

      resources :orderlines, only: [:create, :destroy]
      put 'orderlines/:id/increase', to:'orderlines#increase_item', as: :increase_item
      put 'orderlines/:id/decrease', to:'orderlines#decrease_item', as: :decrease_item
      delete 'orderlines/:id/cancel', to:'orderlines#cancel_item', as: :cancel_item

    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  before_create :set_order_time
  belongs_to :table
  has_many :orderlines
  has_one :restaurant, through: :table

  monetize :amount_cents

  def price_per_order
    price = 0
    self.orderlines.each do |orderline|
      price += orderline.quantity * orderline.item.price
    end
    return price
  end

  def set_order_time
    self.time = Time.now
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_table, only: [:index, :update, :destroy, :clear_table, :delivered, :paid, :price_per_table, :ticket]
  before_action :set_order, only: [:destroy, :delivered, :paid, :ticket]
  before_action :set_restaurant, only: [:index, :update, :destroy, :delivered, :paid, :clear_table, :ticket]

  def index
    @orders_all = @table.orders
    @orders_to_show = @table.orders - @table.orders.where(status: 'deleted') - @table.orders.where(status: 'pending')
    @orders_not_paid = @table.orders.where(paid: false) - @table.orders.where(status: 'deleted') - @table.orders.where(status: 'pending')
    @orders_pending = @table.orders.where(status: 'pending')
    @orders_in_process = @table.orders.where(status: 'in process')
    @orders_delivered = @table.orders.where(status: 'delivered')
    @orders_paid = @table.orders.where(paid: true)
    @total_price = price_per_table
    @index = true
  end

  def update
    @order = Order.find(session[:order_id])
    if session[:order_id]
      session.delete(:order_id)
    end
    @order.time = Time.now
    @order.status = "in process"
    @order.save!
    redirect_to restaurant_table_confirmation_summary_path(@restaurant, @table, @order)
  end

  def destroy
    @order.status = "deleted"
    @order.save!
    redirect_to restaurant_table_orders_path(@restaurant, @table)
    session.delete(:order_id)
  end

  def ticket
    respond_to do |format|
      format.pdf do
        pdf = Prawn::Document.new
        content = []
        content << @restaurant.name.to_s.upcase
        content << " "
        content << "Table number : " + (@order.table.table_number).to_s
        content << "Order passed at " + (@order.time + 60.minutes ).strftime("%H:%M")
        content << " "
        content << "items".upcase
        content << " "
        @order.orderlines.each do |ol|
          content << "- " + ol.item.name.to_s + " x " + ol.quantity.to_s
        end
        pdf.text content.join("\n")
        send_data pdf.render
      end
    end
    @order.printed = true
  end

  def delivered
    @order.status = "delivered"
    @order.save!
    redirect_to restaurant_dashboard_path(@restaurant)
  end

  def paid
    @order.paid = true
    @order.save!
    if params[:format]
      redirect_to restaurant_table_orders_path(@restaurant, @table)
    else
      redirect_to restaurant_dashboard_path(@restaurant)
    end
  end

  def clear_table
    @table.orders.where.not(status:'pending').each do |order|
      order.status = "deleted"
      order.save!
    end
    redirect_to restaurant_dashboard_path(@restaurant)
  end

  private

  def price_per_table
    total_price = 0
    @orders_to_show.each do |order|
      order.orderlines.each do |orderline|
        total_price += orderline.quantity * orderline.item.price
      end
    end
    total_price
  end

  def set_order
    @order = Order.find(params[:id])

  end

  def set_table
    @table = Table.find(params[:table_id])
  end

end

app/views/orders/index.html.erb
<%= render 'shared/browser-tab-title'  %>

<div class="col-sm-6 col-sm-offset-3">
  <div class="box basket text-center">
    <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>

    <h3 class="basket-title">Table <%= @table.table_number %> - summary</h3>
    <p><strong>Total price: <%= humanized_money_with_symbol(@total_price) %></p></strong>
    <% if @orders_not_paid.any? %>
    <p><strong>Warning:</strong> you have <strong><%= @orders_not_paid.count %> </strong> unpaid orders.</p>
    <!-- <p>Make sure they are <button class="btn btn-status-paid-text">paid</button> before reseting the table</p> -->
    <% end %>
    <div class="btn-flex">
      <p><%= link_to 'Dashboard', restaurant_dashboard_path(@restaurant), class: "btn btn-back" %></p>

      <% unless @orders_not_paid.any? %>
      <p><%= link_to 'Reset table', restaurant_table_clear_path(@restaurant, @table), method: :delete, class: "btn btn-clear", :data => {:confirm => 'This will delete all the orders. Confirm?'} %></p>
      <% end %>
    </div>
    <div class="summary-centered">
      <div class="background-summary-centered">
        <% @orders_to_show.sort_by(&:time).reverse.each do |order| %>
        <div class="order-line">
          <span>
            <% if order.paid  %>
              <i class="fa fa-eur" style="color: #53ba81" aria-hidden="true"></i>
            <% else %>
              <%= link_to '<i class="fa fa-square-o" style="color: #53ba81" aria-hidden="true"></i>'.html_safe, restaurant_table_order_paid_path(@restaurant, order.table, order, @index) %>
            <% end %>
          </span>
          <span><strong> <%= (order.time + 1.hour).strftime("%H:%M") %></span></strong>
          <span><%= humanized_money_with_symbol(order.price_per_order) %></span>
          <% if order.status == 'in process' %>
          <p class="btn btn-status-in-process "><%= order.status %></p>
          <% elsif order.status == 'delivered' %>
          <p class="btn btn-status-delivered"><%= order.status %></p>
          <% end %>
        </div>
        <% order.orderlines.each do |orderline| %>
        <div class="item-name">
          <p> - <strong><%= orderline.quantity %> x</strong> <%= orderline.item.name %></p>
        </div>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>