config/routes.rb
Rails.application.routes.draw do
  root to: 'restaurants#home'

  get 'home', to:'restaurants#home', as: :home
  resources :restaurants, only: [:index] do
    put 'kitchen', to: 'restaurants#kitchen', as: :kitchen
    get 'dashboard', to:'restaurants#dashboard', as: :dashboard
    get 'statistics/turnover', to:'restaurants#turnover', as: :turnover
    get 'statistics/metrics', to:'restaurants#metrics', as: :metrics
    resources :tables, only: [:index, :show] do

      resources :items, only: [:index]
      get 'items/basket', to:'items#basket_summary', as: :basket_summary
      get 'items/confirmation/orders/:id', to:'items#confirmation_summary', as: :confirmation_summary

      resources :orders, only: [:index, :update, :destroy] do
        resources :payments, only: [:new, :create]
      end
      delete 'orders', to:'orders#clear_table', as: :clear
      get 'orders/:id/delivered', to:'orders#delivered', as: :order_delivered
      get 'orders/:id/paid', to:'orders#paid', as: :order_paid
      get 'orders/:id/ticket', to: 'orders#ticket', as: :order_ticket

      resources :orderlines, only: [:create, :destroy]
      put 'orderlines/:id/increase', to:'orderlines#increase_item', as: :increase_item
      put 'orderlines/:id/decrease', to:'orderlines#decrease_item', as: :decrease_item
      delete 'orderlines/:id/cancel', to:'orderlines#cancel_item', as: :cancel_item

    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  extend FriendlyId
  friendly_id :create_horrible_id, use: :slugged

  has_many :items
  has_many :tables
  has_many :orders, through: :tables


  def status_kitchen
    if self.kitchen
      self.kitchen = false
    else
      self.kitchen = true
    end
    self.save!
  end

  def average_order_price
    order_by_day = orders.group_by_day(:time, week_start: :mon)
    orders.where(paid: true).average(:amount_cents) / 100.0
  end

  def unpaid_orders_count
    orders.where(paid: false).count
  end

  def list_of_categories
    list = []
    self.items.each do |item|
      unless list.include?(item.category)
        list << item.category
      end
    end
    list
  end

  private

  def create_horrible_id
    SecureRandom.uuid
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:dashboard, :kitchen, :turnover, :metrics]

  def home
    #code
  end

  def turnover
    #code
  end

  def metrics
    #code
  end

  def index
    @restaurants = Restaurant.all
  end

  def dashboard
    @tables = @restaurant.tables
    @orders_all =  @restaurant.orders
    @orders_pending = @restaurant.orders.where(status: 'pending')
    @orders_in_process = @restaurant.orders.where(status: 'in process').order(:time).reverse
    @orders_delivered = @restaurant.orders.where(status: 'delivered').order(:time).reverse
    @orders_deleted = @restaurant.orders.where(status: 'deleted')
    @orders_not_yet_paid = @restaurant.orders.where(paid: false) - @orders_deleted - @orders_pending

    @dangerous_orders = []
    @orders_not_yet_paid.each do |order|
      if (Time.now - order.time) > 60.minutes
        @dangerous_orders << order
      end
    end
    @dangerous_orders

    @active_orders = @orders_in_process + @orders_delivered

    @active_tables = 0
    @restaurant.tables.each do |table|
      if (table.orders - @orders_deleted - @orders_pending).any?
        @active_tables += 1
      end
    end
    @active_tables

    @occupied_tables = (@active_tables.to_f/@tables.count.to_f) * 100

  end

  def kitchen
    @restaurant.status_kitchen
    redirect_to restaurant_dashboard_path(@restaurant)
  end
end

app/views/restaurants/dashboard.html.erb
<style>
#r-button  {
  color: #ce6564;
  border: none;
  background: inherit;
}
</style>


<script> setTimeout(location.reload.bind(location), 60000); </script>


<body>
  <%= render 'shared/browser-tab-title'  %>
  <%= render 'shared/sidebar-left' %>
  <%= render 'shared/sidebar-right' %>
  <div id="container">


    <div class="orderstat box">
      <div>
        <h5>Orders in process</h5>
      </div>
      <% @orders_in_process.each do |order| %>
      <div>
        <div class="panel-group">
          <div class="panel panel-default">
            <div class="panel-heading">
              <div class="dashboard-order">
                  <span class="words-dashboard">
                    <% if order.paid  %>
                    <i class="fa fa-eur" style="color: #53ba81" aria-hidden="true"></i>
                    <% else %>
                    <%= link_to '<i class="fa fa-square-o" style="color: #53ba81" aria-hidden="true"></i>'.html_safe, restaurant_table_order_paid_path(@restaurant, order.table, order) %>
                    <% end %>
                  </span>
                <a class="dash" data-toggle="collapse" href="#collapse-<%=  order.id %>">

                <span style="margin-right: 10px;  margin-left: -10px;">Table <%= order.table.table_number %></span>


                 <span style="margin-right: 10px;"><%= (order.time + 60.minutes ).strftime("%H:%M") %></span>

                 <span><%= humanized_money_with_symbol(order.price_per_order) %></span>


                <%= link_to '<i class="fa fa-arrow-right btn btn-default" style="color: #feb632; font-size:17px"></i>'.html_safe, restaurant_table_order_delivered_path(@restaurant, order.table, order) %>
                </a>
              </div>
            </div>
            <div id="collapse-<%=  order.id %>" class="panel-collapse collapse">
              <ul class="list-group">
                <% order.orderlines.each do |orderline| %>
                <li class="list-group-item"><%= orderline.quantity %> x <%= orderline.item.name %> - <%= humanized_money_with_symbol(orderline.quantity * orderline.item.price) %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>

    <div class="orderstat box">
      <div>
        <h5>Orders delivered</h5>
      </div>
      <% @orders_delivered.each do |order| %>
      <div>
        <div class="panel-group">
          <div class="panel panel-default">
            <div class="panel-heading">
              <div class="dashboard-order">
                  <span class="words-dashboard">
                    <% if order.paid  %>
                    <i class="fa fa-eur" style="color: #53ba81" aria-hidden="true"></i>
                    <% else %>
                    <%= link_to '<i class="fa fa-square-o" style="color: #53ba81" aria-hidden="true"></i>'.html_safe, restaurant_table_order_paid_path(@restaurant, order.table, order) %>
                    <% end %>
                  </span>
                <a class="dash" data-toggle="collapse" href="#collapse-<%=  order.id %>" style="margin-right: 20px;">
                  <span style="margin-right: 10px; margin-left: -10px;">
                    Table <%= order.table.table_number %>
                  </span>
                  <span style="margin-right: 10px;">
                    <%= (order.time + 60.minutes ).strftime("%H:%M") %>
                  </span>
                    <%= humanized_money_with_symbol(order.amount) %>
                </a>
              </div>
            </div>
            <div id="collapse-<%=  order.id %>" class="panel-collapse collapse">
              <ul class="list-group">
                <% order.orderlines.each do |orderline| %>
                <li class="list-group-item"><%= orderline.quantity %> x <%= orderline.item.name %> - <%= humanized_money_with_symbol(orderline.quantity * orderline.item.price) %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>






  </div>
</body>

app/views/restaurants/home.html.erb
<div class="banner-homepage" style="background-image: linear-gradient(-225deg, rgba(255, 240, 0, 0.2) 0%, rgba(62, 54, 0, 0.3) 30%), url(<%= image_path "homepage.jpg"%>); background-position: center;">

  <div class="banner-content">
    <h1>Digitalize your restaurant thanks to Chronos</h1>
    <!-- Action button to be implemented once ready -->
    <!-- div class="btn btn-homepage">
      Get your digital menu now !
    </div> -->
  </div>
</div>


<a href="#" class="scroll-down" address="true"></a>
<section class="ok">


  <!-- FEATURES BEGIN -->
  <section id="features" class="img-block-3col">
    <div class="container">
      <div class="title" style="text-align: center;">
        <h2>Key Features</h2>
        <p>Here are some of the features that Chronos has to offer</p>
      </div>
      <div class="row">
        <div class="col-sm-4">
          <ul class="list-unstyled">
            <li>
              <h3><%= image_tag 'widget.png' %> Digital Menu</h3>
              <p style="text-align: justify;">Your customers have now access to the whole menu through any device, we will ensure that your menu meet the highest standards in terms of design and ergonomy.</p>
            </li>
            <li>
              <h3><%= image_tag 'preferences.png' %> Statistics</h3>
              <p style="text-align: justify;">Thanks to all the data gathered, you will be able to get an overview of your restaurant activity to permit a better understanding of your business.</p>
            </li>
            <li>
              <h3><%= image_tag 'award-48.png' %> Entertaining aspect for your customers</h3>
              <p style="text-align: justify;">Enhance your customer's experience with the technology, no app downloading is needed. Everything will be directly available from the browser to ensure an ordering process always quicker.</p>
            </li>
          </ul>
        </div>
        <div class="col-sm-4">
          <%= image_tag 'iphone2.png', class: "iphone" %>
        </div>
        <div class="col-sm-4">
          <ul class="list-unstyled item-list-left item-list-big">
            <li>
              <h3><%= image_tag 'barcode-qr.png' %> Order with a QR-code</h3>
              <p style="text-align: justify;">Streamline the ordering process for you customers by allowing them to access the menu through a scannable QR-code.</p>
            </li>
            <li>
              <h3><%= image_tag 'lock.png' %> Integrated Payment</h3>
              <p style="text-align: justify;">Customers can pay for their orders quickly and safely by card during the process, while retaining the option to pay by cash.</p>
            </li>
            <li>
              <h3><%= image_tag 'diamond.png' %> Focus more on the services that matter</h3>
              <p style="text-align: justify;">Chronos automates the actions with the less added-value, your staff will then be able to focus way more on the activities that are really enhancing your customer's experience.</p>
            </li>
          </ul>
        </div>


      </div>
    </div>
  </section>

  <section class="img-block-2col">

    <div class="banner2-homepage" style="background-image: linear-gradient(-225deg, rgba(255, 240, 0, 0.2) 0%, rgba(62, 54, 0, 0.3) 30%), url(<%= image_path "wood.jpg"%>); background-position: center;">

        <div class="row">
      <div class="container">


      <div class="banner-content demo-align col-sm-6">
        <h1>Your whole restaurant at your fingertips</h1>
      </div>

      <div class="col-sm-6">
        <%= image_tag 'ipad-chronos.png', class: "Ipad" %>
      </div>
    </div>
  </div>
  </div>

  </section>


  <section>

  <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
 <!--  <div id="footer-description">
  </div> -->
  <div class="footer-copyright">
    <strong>©</strong> 2017 Chronos All rights reserved.
  </div>
</div>

  </section>

app/views/restaurants/index.html.erb
<div class="container">
  <h2>They decided to trust us and to work with us</h2>
  <ul>
    <% @restaurants.each do |restaurant|%>
    <li>
      <div class="container" style="margin-bottom: 100px">
        <%= restaurant.id %>. <u>Name</u>: <%= restaurant.name %>. <u>Name Address</u>: <%= restaurant.address %>
        <h3>What your client will see</h3>
        <p>See for yourself how it works. If you want to see what your clients will see, click here below</p>
        <%= link_to "go to the tables for this restaurant", restaurant_tables_path(restaurant), class: "btn btn-info" %>
        <h3>your dashboard</h3>
        <p>See for yourself what your dashboard as a restaurant owner will look like</p>
        <%= link_to "go to dashboard for this restaurant", restaurant_dashboard_path(restaurant), class: "btn btn-info" %>
      </div>
    </li>
    <% end %>
  </ul>
</div>

app/views/restaurants/metrics.html.erb
<%= render 'shared/browser-tab-title'  %>

<% Groupdate.time_zone = "Brussels" %>
<div class="container">
  <h3 class="text-center">Statistics: <%= @restaurant.name %> </h3>
  <div class="box">
  <div class="chart">
    <h4 class="text-center"><%= DateTime.now.strftime("%A, %b %d") %></h4>
    <p class="text-center">Number of orders by hour</p>
    <%= column_chart @restaurant.orders.group_by_hour_of_day(:time, format: "%l %P").count %>
  </div>
  <div class="chart">
    <h4 class="text-center">Number of orders by day</h4>
    <%= line_chart @restaurant.orders.group_by_day(:time, week_start: :mon).count %>
  </div>
  <!-- <div class="chart">
    <h4 class="text-center">Number of orders by week</h4>
    <%= line_chart @restaurant.orders.group_by_week(:time, week_start: :mon).count %>
  </div> -->


  <div class="text-center">
    <%= link_to 'Dashboard', restaurant_dashboard_path(@restaurant), class: "btn btn-back" %>
  </div>
  </div>
</div>

app/views/restaurants/statistics.html.erb
<%= render 'shared/browser-tab-title'  %>

<% Groupdate.time_zone = "Brussels" %>
<div class="container">
  <h3 class="text-center">Statistics: <%= @restaurant.name %> </h3>
  <div class="box">
  <div class="chart">
    <h4 class="text-center"><%= DateTime.now.strftime("%A, %b %d") %></h4>
    <p class="text-center">Number of orders by hour</p>
    <%= column_chart @restaurant.orders.group_by_hour_of_day(:time, format: "%l %P").count %>
  </div>
  <div class="chart">
    <h4 class="text-center">Number of orders by day</h4>
    <%= line_chart @restaurant.orders.group_by_day(:time, week_start: :mon).count %>
  </div>
  <!-- <div class="chart">
    <h4 class="text-center">Number of orders by week</h4>
    <%= line_chart @restaurant.orders.group_by_week(:time, week_start: :mon).count %>
  </div> -->
  <div class="chart">
    <h4 class="text-center">Turnover (€/day)</h4>
    <%= column_chart @restaurant.orders.group_by_day(:time).sum("amount_cents / 100") %>
  </div>

  <div class="text-center">
    <%= link_to 'Dashboard', restaurant_dashboard_path(@restaurant), class: "btn btn-back" %>
  </div>
  </div>
</div>

app/views/restaurants/turnover.html.erb
<% Groupdate.time_zone = "Brussels" %>
<div class="container">
  <h3 class="text-center">Statistics: <%= @restaurant.name %> </h3>
  <div class="box">

  <div class="chart">
    <h4 class="text-center">Turnover (€/day)</h4>
    <%= column_chart @restaurant.orders.group_by_day(:time).sum("amount_cents / 100") %>
  </div>

  <div class="text-center">
    <%= link_to 'Dashboard', restaurant_dashboard_path(@restaurant), class: "btn btn-back" %>
  </div>
  </div>
</div>