config/routes.rb
Rails.application.routes.draw do
  root to: 'restaurants#home'

  get 'home', to:'restaurants#home', as: :home
  resources :restaurants, only: [:index] do
    put 'kitchen', to: 'restaurants#kitchen', as: :kitchen
    get 'dashboard', to:'restaurants#dashboard', as: :dashboard
    get 'statistics/turnover', to:'restaurants#turnover', as: :turnover
    get 'statistics/metrics', to:'restaurants#metrics', as: :metrics
    resources :tables, only: [:index, :show] do

      resources :items, only: [:index]
      get 'items/basket', to:'items#basket_summary', as: :basket_summary
      get 'items/confirmation/orders/:id', to:'items#confirmation_summary', as: :confirmation_summary

      resources :orders, only: [:index, :update, :destroy] do
        resources :payments, only: [:new, :create]
      end
      delete 'orders', to:'orders#clear_table', as: :clear
      get 'orders/:id/delivered', to:'orders#delivered', as: :order_delivered
      get 'orders/:id/paid', to:'orders#paid', as: :order_paid
      get 'orders/:id/ticket', to: 'orders#ticket', as: :order_ticket

      resources :orderlines, only: [:create, :destroy]
      put 'orderlines/:id/increase', to:'orderlines#increase_item', as: :increase_item
      put 'orderlines/:id/decrease', to:'orderlines#decrease_item', as: :decrease_item
      delete 'orderlines/:id/cancel', to:'orderlines#cancel_item', as: :cancel_item

    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :restaurant
  monetize :price_cents
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_table, only: [:index, :basket_summary, :current_order, :confirmation_summary]
  before_action :set_restaurant, only: [:index, :basket_summary, :confirmation_summary]
  before_action :items_quantity

  def index
    @items = {}
    @categories = @restaurant.list_of_categories
    @categories.each do |category|
      @items_category = @restaurant.items.where(category: category)
      @items[category.to_s] = @items_category
    end
    @items
    @orderline = Orderline.new
    @order = current_order
    @price = price_computation_vat(@order)
    @total_price = @price[:total]
  end

  def basket_summary
    @order = current_order
    @price = price_computation_vat(@order)
    @order.amount = @price[:total]
    @order.save!
    @vat = @price[:vat]
    @subtotal = @price[:subtotal]
  end

  def confirmation_summary
    @order = order = Order.find((params[:id]))
    @orderlines = Order.find(params[:id]).orderlines
    @time = Time.now + 20.minutes
    @price = price_computation_vat(@order)
    @vat = @price[:vat]
    @subtotal = @price[:subtotal]
  end

  private

  def items_quantity
    @order = current_order
    @quantity = 0
    @order.orderlines.each do |orderline|
      @quantity += orderline.quantity
    end
    @quantity
  end

  def price_computation_vat(the_order)
    order = the_order
    total = 0
    vat = 0
    order.orderlines.each do |orderline|
      a = orderline.quantity * orderline.item.vat/10000.to_f * orderline.item.price
      vat += a
      t = orderline.quantity * orderline.item.price
      total += t
    end
    return price = {total: total, vat: vat, subtotal: total - vat}
  end

  def set_table
    @table = Table.find(params[:table_id])
  end

  def current_order
    if session[:order_id] == true || Order.where(id: session[:order_id]).any?
      order = Order.find(session[:order_id])
      order.save!
      return order
    else
      order = Order.new(table: @table, status: "pending")
      order.number = 0
      order.save!
      session[:order_id] = order.id
      return order
    end
  end
end

app/views/items/basket_summary.html.erb
<%= render 'shared/browser-tab-title'  %>

<% flash.each do |key, value| %>
<div class="alert alert-<%= key %>" style="margin-bottom: 11px"><%= value %></div>
<% end %>

<div class="box basket text-center">
  <h2 class="basket-title" >My Basket</h2>
  <div class="row">
    <div class="item-order">
      <% @order.orderlines.each do |orderline| %>
      <div class="item-line">
        <div class="item-name">
          <p><strong><%= orderline.quantity %> x</strong> <%= orderline.item.name %></p>
        </div>
        <div class="button-price">
          <p style="padding:1px;"><%= link_to '<i class="fa fa-minus btn btn-default" style="color: #feb632; font-size:17px"></i>'.html_safe, restaurant_table_decrease_item_path(@restaurant, @table, orderline), method: :put%>
            <p style="padding:1px;"><%= link_to '<i class="fa fa-plus btn btn-default" style="color: #feb632; font-size:17px"></i>'.html_safe, restaurant_table_increase_item_path(@restaurant, @table, orderline), method: :put%></p>
            <p style="padding:1px;"><%= link_to '<i class="fa fa-times btn btn-default" style="color: rgba(254, 50, 50, 0.81); font-size:17px"></i>'.html_safe, restaurant_table_cancel_item_path(@restaurant, @table, orderline), method: :delete%></p>
            <p style="padding-left:10px; width:61px;"><%= humanized_money_with_symbol(orderline.item.price) %></p>
          </div>
        </div>
        <% end %>
      </div>
    </div>

    <div style="margin-top: 15px; margin-bottom: -10px;" class="price" id="sub">
      <h6 style="font-size: 14px;">Subtotal</h6>
      <span><%= humanized_money_with_symbol(@subtotal) %></span>
    </div>
    <div class="price" id="sub">
      <h6 style="font-size: 14px;">VAT</h6>
      <span><%= humanized_money_with_symbol(@vat) %></span>
    </div>
    <div class="brico">
      <div class="grey-line-summary">
      </div>
    </div>
    <div class="price" id="total">
        <h6><strong>TOTAL</strong></h6>
        <span style="font-size: 15px;"><%= humanized_money_with_symbol(@order.amount) %></span>
    </div>



    <div class="confirm-order">
      <div class="confirm-order-message">
        <p>Confirm your order</p>
      </div>
      <div class="confirm-order-btns">
        <% # Confirm order without paying / meaning paying later to the restaurant owner %>
        <%= link_to "Pay later", restaurant_table_order_path(@restaurant, @table, @order), method: :patch, class: 'btn btn-pay-later' %>

        <%= form_tag restaurant_table_order_payments_path(@restaurant, @table, @order) do %>

      <script
      src="https://checkout.stripe.com/checkout.js"
      class="stripe-button"
      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
      data-name=" <%= @restaurant.name %>"
      data-email=""
      data-description="<%= pluralize(@quantity, 'item') %>"
      data-amount="<%= @order.amount_cents %>"
      data-currency="<%= @order.amount.currency %>">
      </script>

        <% end %>
        </div>
      </div>

    <div style="margin-bottom: 15px; margin-top: 30px;">
      <%= link_to 'Back to menu', "#{restaurant_table_items_path(@restaurant, @table)}#basket", class: 'btn-back' %>
    </div>

  </div>

app/views/items/confirmation_summary.html.erb
<%= render 'shared/browser-tab-title'  %>

<% flash.each do |key, value| %>
<div class="alert alert-<%= key %>" style="margin-bottom: 10px"><%= value %></div>
<% end %>

<div class="box basket text-center">
  <h2 class="basket-title" >My Order</h2>
  <div class="row">
    <div class="item-order">
      <% @orderlines.each do |orderline| %>
      <div class="confirmation-centered">
        <!-- <div class="item-name"> -->
        <p><strong><%= orderline.quantity %> x</strong> <%= orderline.item.name %></p>
        <p style="min-width: 50px; max-width: 50px"><%= humanized_money_with_symbol(orderline.item.price) %></p>
        <!--   </div> -->
      </div>
      <% end %>
    </div>
  </div>

<div style="margin-top: 15px; margin-bottom: -10px;" class="price" id="sub">
      <h6 style="font-size: 14px;">Subtotal</h6>
      <span><%= humanized_money_with_symbol(@subtotal) %></span>
    </div>
    <div class="price" id="sub">
      <h6 style="font-size: 14px;">VAT</h6>
      <span><%= humanized_money_with_symbol(@vat) %></span>
    </div>
    <div class="brico">
      <div class="grey-line-summary">
      </div>
    </div>
    <div class="price" id="total">
        <h6><strong>TOTAL</strong></h6>
        <span style="font-size: 15px;"><%= humanized_money_with_symbol(@order.amount) %></span>
    </div>

<div class="expected-time">
  <p>Thanks for your order!</p>
  <div style="margin-top: -10px;"><i class="fa fa-clock-o fa-4x" aria-hidden="true"></i></div>
  <p class="expected-time-message">You should approximately receive it around <strong> <%= @time.strftime("%H:%M") %></strong></p>
</div>
<div style="margin-bottom: 15px">
  <%= link_to 'Back to menu', "#{restaurant_table_items_path(@restaurant, @table)}#basket", class: 'btn-back' %>
</div>
<!-- <div style="margin-bottom: 15px">
  <%= link_to 'Print ticket', "#{restaurant_table_order_ticket_path(@restaurant, @table, @order)}.pdf", class: 'btn-back' %>
</div> -->
<div class="footer-links">
  <a href="#"><i class="fa fa-instagram"></i></a>
  <a href="#"><i class="fa fa-facebook"></i></a>
</div>
</div>

app/views/items/index.html.erb
<%= render 'shared/browser-tab-title'  %>
<%= render 'shared/banner'  %>

<% if @restaurant.kitchen %>

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <p id="basket"></p>

  <% @categories.each_with_index do |category, index| %>

  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFour">
      <h4 class="panel-title">
        <div class= "text-center">
          <a class= "btn btn-header" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse-<%= index %>" aria-expanded="true" aria-controls="collapseFour">
            <%= category.capitalize %>
          </a>
        </div>
      </h4>
    </div>
    <div id="collapse-<%= index %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
      <div class="panel-body">
        <div class="item-box">
          <% @items[category.to_s].each do |item|%>
          <div class="item">
            <div class="item-descritption">
              <li>
                <h3><%= item.name %></h3>
                <p style="max-width: 240px"><%= item.description %></p>
                <p id="price-menu"><%= humanized_money_with_symbol(item.price) %></p>
              </li>
            </div>
            <%= simple_form_for([@restaurant, @table, @orderline]) do |f| %>
            <%= f.input :item,  :as => :hidden, :input_html => { :value => item.id } %>
            <%= f.button :button do %>
            <i class="fa fa-plus" style="color: #feb632"></i>
            <% end %>
            <% end  %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <% end %>
</div>

<!-- Basket summary -->

<div>
  <% if @quantity != 0 %>
    <%= link_to restaurant_table_basket_summary_path(@restaurant, @table), method: :get, class: "btn btn-info btn-summary", style: 'width:100%' do %>
      <span class="item-number-basket"><%= @quantity%></span>
    <div>
      <span>Check my basket</span>
    </div>
    <div>
      <%= humanized_money_with_symbol(@total_price) %>
    </div>
    <% end %>
  <% end %>
</div>

<% end  %>